name: LockIt
main: lockit\Main
version: 1.0.0
author: Awzaw
api: [2.0.0]
load: POSTWORLD
commands:
 lockit:
  permission: lockit
  description: Lock Doors
  usage: /lockit then tap a door
permissions:
   lockit.admin:
    default: op
   lockit:
    default: op