name: LockIt
main: awzaw\lockit\Main
version: 1.3.1
author: Awzaw
api: [2.0.0, 3.0.0-ALPHA1, 3.0.0-ALPHA2, 3.0.0-ALPHA3, 3.0.0-ALPHA4, 3.0.0-ALPHA5]
load: POSTWORLD
commands:
 lockit:
  permission: lockit
  description: Lock Doors
  usage: /lockit then tap a door
permissions:
   lockit.admin:
    default: op
   lockit:
    default: op