name: LockIt
main: awzaw\lockit\Main
version: 1.3.2
author: Awzaw
api: [3.0.0-ALPHA5, 3.0.0-ALPHA6]
load: POSTWORLD
commands:
 lockit:
  permission: lockit
  description: Lock Doors
  usage: /lockit then tap a door
permissions:
   lockit.admin:
    default: op
   lockit:
    default: op